language: scala

scala:
  - 2.10.5

services:
  - redis-server

jdk:
  - oraclejdk7

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS

script:
  - "./bin/sbt ++$TRAVIS_SCALA_VERSION clean test"
