language: scala
sudo: false
scala:
  - 2.10.5

services:
  - redis-server

jdk:
  - oraclejdk7
  - openjdk7

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS

script:
  - "./bin/sbt ++$TRAVIS_SCALA_VERSION clean test"
