language: scala

scala:
  - 2.10.5

services:
  - redis-server
  - mongodb

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS

env:
  - PROJECT="zipkin-aggregate"
  - PROJECT="zipkin-anormdb"
  - PROJECT="zipkin-cassandra"
  - PROJECT="zipkin-example"
  - PROJECT="zipkin-hbase"
  - PROJECT="zipkin-kafka"
  - PROJECT="zipkin-mongodb"
  - PROJECT="zipkin-receiver-kafka"
  - PROJECT="zipkin-receiver-scribe"
  - PROJECT="zipkin-redis"
  - PROJECT="zipkin-sampler"
  - PROJECT="zipkin-tracegen"
  - PROJECT="zipkin-web"
  - PROJECT="zipkin-zookeeper"

script:
  - "./bin/sbt \"project $PROJECT\" ++$TRAVIS_SCALA_VERSION clean test"


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false
