language: scala

scala:
  - 2.10.5

services:
  - redis-server
  - mongodb

jdk:
  - oraclejdk7
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  # ensure the build errors if dependencies aren't available
  - travis_retry ./bin/sbt ++$TRAVIS_SCALA_VERSION update

script:
  - ./bin/sbt ++$TRAVIS_SCALA_VERSION clean test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false

env:
  global:
  - PUBLISH_USING_JDK="oraclejdk7"
  - secure: PfR32Jba7xzPHh4q0ufsbKPWdNNx1I0Bl10mDN2VczIkHYW+m023Smtu1lXmCDjgPoydhLsKWS1gTShE6KlDtmw2yNX/XsrhoRvJT4JM8Ac8nrnEnA4wLWoh3ySBlcac9k0ohkOIiY4OBf1unZcp6BHM4d4qg612VvT0EL0fybmtG3sHG/oCmt+qq/+uye1cFTFWxMYpeuL5L84nDjWTuNc1HpNVK8pBo/boP9dz/CHVT+pXwxvlBqd5QyI/TOIvH4h/y01K3jcooHyk3VeK86OfOkmlfuw7PalEE5RLLPQNxbLniXPdQTgKptNdbiosqqI9bfQR8Df25nJm6f/5PGfSNC4fNlvAVrfuWWwMG0fQl+4ZRi84Er+hSu5zpaJxuMiN9/ubwx6dSSOT2v2zar0rnFwcr1VtzxoiU2Dd/LISkQLbEqiFIeI9xHti7zMiZm0OrgAizhYB8PAj96TrUCU8u7vvk5MZMtBw/XiTnSLd4IKOi+sqN6s1i4jFEHxkY6gTs7fQZ03SEYFK4n50GunDsoJ4RKdHVeTtE9FhXUl9zchTwqNWgk14i5dN7gnh/ewME2qq4Ab0iVWXPgc/bJsV25JJu5eUfppYDevZnj5zkIRwGVQ2/3ZMvt8V9BRmtJKF189k0cMjCKRnEe1b0KgW/mcW4CgCKsFsVluh/a8=
  - secure: prD9JN7yXa+wgx6rLXoUm8fU9fddzuTfXNX/iKV6Zqhu68AKZ2Lsf3+uUr7Kjb7FehuK63x3aphKkwHaz41GlbqZCFc0h0CUZFJbknnj4ihP33ATpwouw/jh8IQfHC+ZwQYuzlT/fh33GlVspscTxPZxNMEy2l8iBnPFoYJsxQgPGVJFEk+93vbR+04fHIPypOpuEI2RxOQbZkhZavlrAufeq6gjYAD5WVIRXMpNGDcUjDco4yWdPC7RfPZIuXmTkOEGD6lCwIzpkRclB9+tlqAdDZ+ChoRW5eBoFSvq/TnnLIBsQ1pxHyomfoZ2RHeh5SjLigX8emqrypj/ARnbnbCphAVyxVu9WdabdCMttojJn9dCf6UGdkBa9Ju/W0obrlTIvms5nbCThgPZmabU63j+M6p6USQqxP4XBp8AdoHEteC5+dYqlThUd5SGMsDvdHoUWCEZyZ2sMTBNQiW6kkp6IKcxx2FdR1Qa+30JFqsU25zXJV1mih0/KiJH1WsZ1RZJQmIQnoJH+8hStaW2TKl4qXFOGLmJesm9mENOxIgFc3iCyqNrzfEPwZatdnpDF2ZmKgdRCoIQ4BOrinOdvOG6v1bL+62Q8BY7t2NTAMbSMw2I5aBEKSSjL3sxqdkkD05k2GOBsRoMZcDFTJYEOLkW/BTZuLMWpH7z4TwkhGI=
after_success:
  - sh "$TRAVIS_BUILD_DIR/travis/publish.sh"
