# Run `travis lint` when changing this file to avoid breaking the build.


# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

cache:
  directories:
  # zipkin-ui gets dependencies via NPM
  - $HOME/.npm
  - $HOME/.m2
  - $HOME/kafka_2.11-0.8.2.2

language: java

jdk:
  # needs to be JDK 1.8 as long as we start Kafka 0.8
  - oraclejdk8

services:
  - docker
  - rabbitmq

before_install:

  # Required for Elasticsearch 5 (See https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup)
  - sudo sysctl -w vm.max_map_count=262144

  # Manually install and run zk+kafka as it isn't an available service
  - test -d $HOME/kafka_2.11-0.8.2.2/bin || curl -sSL https://archive.apache.org/dist/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz | bash -c '(cd $HOME; tar -xzf -)'
  - nohup bash -c "cd $HOME/kafka_2.11-0.8.2.2 && bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &"
  - nohup bash -c "cd $HOME/kafka_2.11-0.8.2.2 && bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &"

  # Quiet Maven invoker logs (Downloading... when running zipkin-server/src/it)
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

  # Disable testcontainers checks
  - echo checks.disable=true > ~/.testcontainers.properties

  # Override default travis to use the maven wrapper
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean verify -B

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
