# yamllint --format github .github/workflows/build_server.yml
---
name: build_server

# We don't test documentation-only commits.
on:
  # We run tests on non-tagged pushes to master that aren't a commit made by the release plugin
  push:
    tags: ''
    branches: master
    paths-ignore: '**/*.md'
  # We also run tests on pull requests targeted at the master branch.
  pull_request:
    branches: master
    paths-ignore: '**/*.md'

jobs:
  build_server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:  # test.yml already tests ubuntu
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # full git history for license check
      # Setup latest JDK. We do this to ensure users don't need to use the same version as our
      # release process. Release uses JDK 11, the last version that can target 1.6 bytecode.
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache NPM Packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-packages-${{ hashFiles('zipkin-lens/package-lock.json') }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Execute Server Build
        # Skips tests and license to run faster and allow shallow clones
        run: ./mvnw -T1C -q --batch-mode -DskipTests --also-make -pl zipkin-server clean package
        shell: bash
