name: Continuous Build Server
on: [push, pull_request]

jobs:
  build:
    name: Build Server
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10
      # Setup latest JDK. We do this to ensure users don't need to use the same version as our
      # release process. Release uses JDK 11, the last version that can target 1.6 bytecode.
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache NPM Packages
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-packages-${{ runner.os }}-${{ hashFiles('zipkin-lens/package-lock.json') }}
      - name: Cache Maven Modules
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: m2-repository-${{ hashFiles('**/pom.xml') }}
      - name: Cache Maven Wrapper
        uses: actions/cache@v1
        with:
         path: .mvn/wrapper
         key: mvn-wrapper-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties') }}
      - name: Show version
        run: ./mvnw -version
        shell: bash
      - name: Execute Server Build
        run: ./mvnw -q --batch-mode -DskipTests --also-make -pl zipkin-server clean install
        shell: bash
        env:
          CI: true
